### ISSUE TITLE
Define tech stack for gravity

### ISSUE THREAD

**Issue by xhipster** [cybercongress/gravity#22]
Currently, the problem is the following:

@dimakorzhovnik is working with react and as a result, we implemented cyb and gravity lib using react

@Jonybang is working with vue and that is why the virus is implemented in vue.

It's a bad idea to work like this as we must spend resources to implement and test things twice.

My proposal: switch to
 https://svelte.dev/ instead of both react and vue. It is cool, fast, lean and hurts nobody. 

In order to convince me to use either react or vue, please show me the proof that you will be able to produce at least 3x less code than svelte does.

I am starting to block any pull requests both into cyb and cyb-virus before we settle this out.

@dimakorzhovnik @Jonybang

**Comment by Jonybang** [comment]
I dont think that is a good idea. Because react have a huge community, vue have a little smaller community, there is many tools already built on react and vue, many questions are answered in both of them, but not for svetle.
I think solution should be done based on not "less code", but on experience and community

**Comment by xhipster** [comment]
> I think a solution should be done based on not "less code", but on experience and community

Wrong assumption. Web3 opportunity is, in fact, lean and fast computing. Performance and bandwidth is everything that is important in the end. It is a way simpler to tradeoff some features (because, you know, we can) than. 

In our gravity library, we need something like 15-20 elements in order to **radically** to simplify interface development.

**Comment by Jonybang** [comment]
Size of application is matter, yes, but for NOW if we will spent a half of year to deal with new framework - it will be very sad.

**Comment by xhipster** [comment]
1. It is very sad to load megabytes of data of ugly code again and again because of laziness
2. I don't think we will spend so much time. Probably a couple of months.
3. Even if that will cost us half a year, 10x reduction in speed and network usage is a good enough competitive advantage for the goal we want to achieve.

**Comment by xhipster** [comment]
> Size of application is matter, yes, but for NOW if we will spent a half of year to deal with new framework - it will be very sad.

And it is not a framework, but compilator.

**Comment by npopeka** [comment]
If we want to make the Gravity component library the most popular. as a product, you need to support and react and vue and svelte and maybe more. Developers have a problem transitioning from one framework to another. The ability to get these communities exceeds, as it seems to me, the labor costs of simultaneously supporting several frameworks.

**Comment by xhipster** [comment]
Guys, Right now I want to solve one, but a very particular problem - creating the amazing interface for our apps. A page with 100 bytes useful information and almost no formatting at all could not weight 100kbytes.

**Comment by xhipster** [comment]
Moving to Vue will not allow us to stay in time. First releases will be based on React including all involved applications. Thanks, everybody for discussion and involvement.
